name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (latest stable version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Uses the latest Python 3.x version
          cache: 'pip' # Caches pip dependencies for faster runs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: false # Fail the job if this step fails
        env:
          PIP_NO_CACHE_DIR: false # Allow pip caching

      # Step 4: Run the main script
      - name: Run main script
        run: |
          python3 ARMAN/main.py
        continue-on-error: false # Fail the job if this step fails

      # Step 5: Capture and display detailed error logs (if any)
      - name: Show error logs (if failed)
        if: failure()
        run: |
          echo "Error occurred. Displaying relevant logs..."
          echo "Python version:"
          python3 --version
          echo "Pip version:"
          pip --version
          echo "Installed packages:"
          pip list
          echo "Checking for missing dependencies or issues..."
          pip check
          echo "Directory structure:"
          ls -R

      # Step 6: Archive logs (optional, for debugging)
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            *.log
            *.txt
          retention-days: 7
